/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AllSearch: typeof import('./components/Menu/AllSearch.vue')['default']
    BellBtn: typeof import('./components/btn/BellBtn.vue')['default']
    DeviceMenu: typeof import('./components/main/Home/DeviceMenu.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FoldSwiper: typeof import('./components/card/FoldSwiper.vue')['default']
    HeaderMenu: typeof import('./components/Menu/HeaderMenu.vue')['default']
    LeftMenu: typeof import('./components/Menu/LeftMenu.vue')['default']
    LoginForm: typeof import('./components/main/Login/LoginForm.vue')['default']
    MenuSwiper: typeof import('./components/main/Home/MenuSwiper.vue')['default']
    OrderTotal: typeof import('./components/main/Home/OrderTotal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./components/btn/ThemeSwitch.vue')['default']
    WelcomeCard: typeof import('./components/card/WelcomeCard.vue')['default']
  }
}
